services:
  - type: web
    name: highrise-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: PORT
        value: 10000
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true